# Generated by Django 5.0.3 on 2024-08-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
